name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      # Skipped dependency submission step
      # - name: Submit Maven Dependency Tree
      #   uses: advanced-security/maven-dependency-submission-action@v1
      #   with:
      #     args: dependency-tree

      - name: Run tests
        run: mvn test
